openapi: 3.0.1
info:
  title: CACHAÇARIA API
  description: 'API DE LOJAS QUE VENDEM CACHAÇA.'
  version: 1.0.3
  termsOfService: http://swagger.io/terms/
  contact:
    name: Repositorio Gitlab
    url: https://gitlab.com/g.sdomingues/contrato-swagger
tags: 
  - name: Cliente
  - name: Produto 
  - name: Revendedor
    
externalDocs:
  description: Modelagem MER - Database. 
  url: https://www.figma.com/file/cn7AaRafBq7dEgY1XvaDxm/Untitled?node-id=0%3A1

servers: 
# Added by API Auto Mocking Plugin
- description: API TESTE CACHACARIA
  url: https://6169b04c09e030001712c530.mockapi.io/cachaca/
  

paths:
  /Cliente:
    get:
      tags: 
      - Cliente
      summary: Recuperando todos os dados de Clientes.
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Cliente"
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar."
        
    post:
      tags: 
      - Cliente
      summary: Criando um novo Cliente.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                cpf:
                  type: string
                ano_nascimento:
                  type: number
                endereco:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida"
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
        
  /Cliente/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      tags: 
      - Cliente
      summary: Recuperando um Cliente pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  cpf:
                    type: string
                  ano_nascimento:
                    type: number
                  endereco:
                    type: string
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida"
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
              
    delete:
      tags: 
      - Cliente
      summary: Deleta um Cliente pelo ID
      responses:
        200:
          description: Apagado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  cpf:
                    type: string
                  ano_nascimento:
                    type: number
                  endereco:
                    type: string
                  
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado."
              
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida."
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lida"
    put:
      tags: 
      - Cliente
      summary: Atualiza um Cliente pelo ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                cpf:
                  type: string
                no_nascimento:
                  type: number
                endereco:
                  type: string
      responses:
        200:
          description: Sucesso
          content:
            appication/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  cpf:
                    type: string
                  ano_nascimento:
                    type: number
                  endereco:
                    type: string
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida"
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"

  /Produto:
    get:
      tags: 
      - Produto
      summary: Recuperando todos os produtos
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/produto"
        
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
    post:
      tags: 
        - Produto
      summary: Criando um novo produto
      requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  preco:
                    type: number
                  sabor:
                    type: string
                  validade:
                    type: string
                    format: date
                  clientes_cpf:
                    type: array
                    items:
                      properties:
                        cpf:  
                          type: string
                  revendedora_cnpj:
                    type: array
                    items:
                      properties:
                        cnpj:
                          type: string
                      
                          
                        
                
      responses:
        200:
          description: sucesso
          content:
            application/json:
              example: sucesso
              schema:
                $ref: "#/components/schemas/produto"
        
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida"
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
    
  /Produto/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      tags: 
      - Produto
      summary: Recuperando um produto pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/produto"
        
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
            
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
    
    delete:
      tags: 
      - Produto
      summary: Deleta um produto pelo ID
      responses:
        200:
          description: Apagado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  preco:
                    type: number
                  sabor:
                    type: string
                  validade:
                    type: string
                    format: date
                            
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
            
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
          
    put:
      tags: 
      - Produto
      summary: Atualiza um produto pelo ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                preco:
                  type: number
                sabor:
                  type: string
                validade:
                  type: string
                  format: date
      responses:
        200:
          description: Sucesso
          content:
            appication/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  preco:
                    type: number
                  sabor:
                    type: string
                  validade:
                    type: string
                    format: date
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida"
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
  
  /revendedora:
    get:
      tags: 
      - Revendedor
      summary: Recuperando todas as revendedoras 
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/revendedor"
        
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
    
    post:
      tags: 
        - Revendedor
      summary: Criando um novo produto
      requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  endereco:
                    type: string
                  cnpj:
                    type: string
              
      responses:
        200:
          description: sucesso
          content:
            application/json:
              example: sucesso
              schema:
                $ref: "#/components/schemas/revendedor"
        
        400:
          description: o servidor não entendeu a requisição pois está com uma sintaxe inválida.
          content:
            application/json:
              example: "o servidor não entendeu a requisição pois está com uma sintaxe inválida"
        
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"

  /Revendedor/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      tags: 
      - Revendedor
      summary: Recuperando um revendedor pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/revendedor"
        
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
    
    delete:
      tags: 
      - Revendedor
      summary: Deleta um produto pelo ID
      responses:
        200:
          description: Apagado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  endereco:
                    type: string
                  cnpj:
                    type: string
                            
        404:
          description: O servidor não pode encontrar o recurso solicitado.
          content:
            application/json:
              example: "O servidor não pode encontrar o recurso solicitado"
              
        500:
          description: O servidor encontrou uma situação com a qual não sabe lidar.
          content:
            application/json:
              example: "O servidor encontrou uma situação com a qual não sabe lidar"
          
    put:
      tags: 
      - Revendedor
      summary: Atualiza um revendedor pelo ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  nome:
                    type: string
                  endereco:
                    type: string
                  cnpj:
                    type: string
      responses:
        200:
          description: Sucesso
          content:
            appication/json:
              schema:
                type: object
                properties:
                    nome:
                      type: string
                    endereco:
                      type: string
                    cnpj:
                      type: string
        
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        cpf:
          type: string
        no_nascimento:
          type: number
        endereco:
          type: string
        Revendedor: 
          type: array
          items:
            $ref: "#/components/schemas/revendedor"
        
    produto:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        preco:
          type: number
        sabor:
          type: string
        validade:
          type: string
          format: date
        Revendedor:
          type: array
          items:
            $ref: "#/components/schemas/revendedor"
        
 
    
    revendedor:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        endereco:
          type: string
        cnpj:
          type: string
       
